name = "myway"
type = "javascript"
account_id = "4c70b3caca54ead29028a7efea58aabd"
workers_dev = true
compatibility_date = "2025-06-15"
main = "src/index.js"

# Assets (static files) will be uploaded to KV via `wrangler publish`
[site]
  bucket = "./public"
  