name = "canberra-transit-guide"
type = "javascript"
account_id = "4c70b3caca54ead29028a7efea58aabd"
workers_dev = true
route = ""
zone_id = ""

# Assets (static files) will be uploaded to KV via `wrangler publish`
[site]
  bucket = "./public"
  entry-point = "src"